[versions]
# App
app-version-code = "1"
app-version-name = "1.0.0"
sdk-min = "24"
sdk-target = "33"
sdk-compile = "33"

# Plugins
android-gradle = "8.1.0-alpha06"
kotlin = "1.8.0"
kotlin-coroutines = "1.6.4"
kotlin-serialization = "1.4.1"

# Libs
android-core-ktx = "1.9.0"
activity = "1.6.1"
navigation = "2.5.3"
retrofit = "2.9.0"
room = "2.4.3"
lifecycle = "2.6.0-alpha03"
compose-bom = "2023.01.00"
compose-compiler = "1.4.0"
coil = "2.2.2"
#constraintlayout = "1.0.1"

# test libraries
test-junit = "4.13.2"
test-mockk = "1.13.3"

# android test libraries
test-android-runner = "1.5.1"

[plugins]

android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

[libraries]


androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "android-core-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
lyfecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lyfecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lyfecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
#compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout" }

# test libraries
test-junit = { module = "junit:junit", version.ref = "test-junit" }
test-kotlin = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
test-mockk = { module = "io.mockk:mockk", version.ref = "test-mockk" }

# Android test libraries
test-android-compose = { group = "androidx.compose.ui", name = "ui-test-junit4" }
test-android-runner = { module = "androidx.test:runner", version.ref = "test-android-runner" }

[bundles]
compose = [
    "compose-ui",
    "compose-ui-graphics",
    "compose-ui-preview",
    "compose-material3",
    "activity-compose",
    "compose-ui-util"
   # "compose-constraintlayout"
]

compose-debug = [
    "compose-ui-tooling",
    "compose-ui-manifest"
]

lyfecycle = [
    "lyfecycle-compose",
    "lyfecycle-runtime",
    "lyfecycle-runtime-compose"
]

test-common = [
    "test-junit",
    "test-kotlin",
    "test-kotlin-coroutines",
    "test-mockk"
]

test-android = [
    "test-android-compose",
    "test-android-runner"
]